version: "3.8"

services:
  # Service Backend (Go API)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sejiwa-api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - sejiwa-net

  # Service Database (PostgreSQL)
  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    container_name: sejiwa-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sejiwa
      POSTGRES_PASSWORD: sejiwa
      POSTGRES_DB: sejiwa
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sejiwa-net

  # Service Nginx (Frontend + Reverse Proxy)
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile # Menggunakan Dockerfile yang baru kita buat
    container_name: sejiwa-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Volume untuk sertifikat SSL dari Certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # Volume untuk proses verifikasi domain oleh Certbot
      - ./certbot-data:/var/www/certbot
    depends_on:
      - api
    networks:
      - sejiwa-net

networks:
  sejiwa-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
