# FILE: sejiwa/docker-compose.yml
# Versi final yang sudah disesuaikan untuk berjalan di belakang reverse proxy

version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sejiwa-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - CORS_ALLOWED_ORIGINS=http://sejiwa.horus.my.id,https://sejiwa.horus.my.id
    depends_on:
      - db
    networks:
      # Terhubung ke jaringan internal khusus untuk aplikasi sejiwa
      - sejiwa-net

  # Service untuk Database PostgreSQL
  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    container_name: sejiwa-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sejiwa
      POSTGRES_PASSWORD: sejiwa
      POSTGRES_DB: sejiwa
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      # Juga terhubung ke jaringan internal khusus untuk aplikasi sejiwa
      - sejiwa-net

  # Service untuk Frontend (Nginx yang menyajikan file React)
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: sejiwa-nginx
    restart: unless-stopped
    # Perhatikan: Bagian 'ports' sudah DIHAPUS dari sini.
    # Kontainer ini tidak lagi terhubung langsung ke dunia luar.
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot-data:/var/www/certbot
    depends_on:
      - api
    networks:
      # Terhubung ke dua jaringan:
      # 1. Jaringan internal 'sejiwa-net' untuk bicara dengan 'api'
      - sejiwa-net
      # 2. Jaringan eksternal 'nginx-proxy' agar bisa ditemukan oleh reverse proxy utama
      - nginx-proxy

# Deklarasi jaringan yang digunakan di atas
networks:
  # Jaringan internal untuk komunikasi antar service di dalam aplikasi sejiwa
  sejiwa-net:
    driver: bridge
  # Jaringan bersama yang juga akan digunakan oleh reverse proxy utama
  nginx-proxy:
    external: true # Menandakan bahwa jaringan ini dibuat di luar file ini

# Deklarasi volume untuk menyimpan data database secara permanen
volumes:
  postgres_data:
    driver: local
